name: Update Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python etl/extract_mexico_stats.py

      - name: Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "⚙️ Update stats from extract_mexico_stats.py"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/carlsLobato/futboard.git HEAD:main
          else
            echo "Nothing to commit"
          fi
